// Package state renders STATE.md — the human-readable, git-tracked
// projection of the tracker's current state (§9). It is a pure DB→bytes
// function: the same database renders the same bytes, which is what lets
// R14 assert STATE.md byte-equals its render (§7) and what makes the file
// a clean diff surface. Born at S8a because `init` is its first consumer;
// the S8c `state` verb and R14 reuse it through the pipeline's render hook.
//
// STATE.md is the generated surface durable-doc rule 1 points prose AT
// (§9): it holds only what the DB enumerates, so nothing here is copied,
// only projected. It carries no dump digest — a digest would depend on the
// serialized dump, and a pure DB projection stays deterministic without one.
package state

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// recentEvents is the fixed window §9 renders: the last N events, newest
// first. Bounded so STATE.md stays O(active), never O(history) (D15).
const recentEvents = 10

// Render returns the deterministic STATE.md bytes for db: UTF-8, LF,
// trailing newline, fixed sections in fixed order.
func Render(ctx context.Context, db *sql.DB) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Project state\n\nGenerated by `selftracked state`; do not hand-edit " +
		"(the pre-commit hook regenerates it). Numbers here are the database's, " +
		"not a copy — see `selftracked list`/`show`/`log` for detail.\n")
	if err := renderActiveEpics(ctx, db, &b); err != nil {
		return nil, err
	}
	if err := renderTaskQueue(ctx, db, &b); err != nil {
		return nil, err
	}
	if err := renderRecentActivity(ctx, db, &b); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

// renderActiveEpics lists ACTIVE epics (slug ASC) with their story tallies.
func renderActiveEpics(ctx context.Context, db *sql.DB, b *strings.Builder) error {
	b.WriteString("\n## Active epics\n\n")
	rows, err := db.QueryContext(ctx, `
		SELECT e.slug, e.goal,
		  COUNT(CASE WHEN s.status = 'DONE' THEN 1 END),
		  COUNT(CASE WHEN s.status = 'IN-PROGRESS' THEN 1 END),
		  COUNT(CASE WHEN s.status = 'READY' THEN 1 END),
		  COUNT(CASE WHEN s.status = 'BLOCKED' THEN 1 END)
		FROM epics e LEFT JOIN stories s ON s.epic = e.slug
		WHERE e.status = 'ACTIVE'
		GROUP BY e.slug, e.goal ORDER BY e.slug`)
	if err != nil {
		return fmt.Errorf("state: active epics: %w", err)
	}
	defer func() { _ = rows.Close() }()
	found := false
	for rows.Next() {
		var slug, goal string
		var done, inProgress, ready, blocked int64
		if err := rows.Scan(&slug, &goal, &done, &inProgress, &ready, &blocked); err != nil {
			return fmt.Errorf("state: active epics: %w", err)
		}
		found = true
		fmt.Fprintf(b, "- **%s** — %s\n  (stories: %d done, %d in progress, %d ready, %d blocked)\n",
			slug, goal, done, inProgress, ready, blocked)
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("state: active epics: %w", err)
	}
	if !found {
		b.WriteString("_none_\n")
	}
	return nil
}

// renderTaskQueue prints the counts of the three open task states.
func renderTaskQueue(ctx context.Context, db *sql.DB, b *strings.Builder) error {
	b.WriteString("\n## Task queue\n\n")
	counts := map[string]int64{}
	rows, err := db.QueryContext(ctx,
		`SELECT status, COUNT(*) FROM tasks WHERE status IN ('OPEN','IN-REVIEW','NEEDS-TRIAGE') GROUP BY status`)
	if err != nil {
		return fmt.Errorf("state: task queue: %w", err)
	}
	defer func() { _ = rows.Close() }()
	for rows.Next() {
		var status string
		var n int64
		if err := rows.Scan(&status, &n); err != nil {
			return fmt.Errorf("state: task queue: %w", err)
		}
		counts[status] = n
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("state: task queue: %w", err)
	}
	for _, s := range []struct{ label, status string }{
		{"open", "OPEN"}, {"in review", "IN-REVIEW"}, {"needs triage", "NEEDS-TRIAGE"},
	} {
		fmt.Fprintf(b, "- %s: %d\n", s.label, counts[s.status])
	}
	return nil
}

// renderRecentActivity prints the last recentEvents events, newest first.
func renderRecentActivity(ctx context.Context, db *sql.DB, b *strings.Builder) error {
	b.WriteString("\n## Recent activity\n\n")
	rows, err := db.QueryContext(ctx,
		`SELECT at, entity, event, detail FROM events ORDER BY seq DESC LIMIT ?`, recentEvents)
	if err != nil {
		return fmt.Errorf("state: recent activity: %w", err)
	}
	defer func() { _ = rows.Close() }()
	found := false
	for rows.Next() {
		var at, entity, event, detail string
		if err := rows.Scan(&at, &entity, &event, &detail); err != nil {
			return fmt.Errorf("state: recent activity: %w", err)
		}
		found = true
		if detail == "" {
			fmt.Fprintf(b, "- `%s` %s %s\n", at, entity, event)
		} else {
			fmt.Fprintf(b, "- `%s` %s %s: %s\n", at, entity, event, detail)
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("state: recent activity: %w", err)
	}
	if !found {
		b.WriteString("_none yet_\n")
	}
	return nil
}
