// Package verb holds the catalog's task-lifecycle verbs and the shared
// write pipeline every write verb runs through (§6.1): version gate →
// §8.4 divergence core → EXCLUSIVE connection → one transaction (mutation
// + events row) → commit → regenerate the dump (and STATE.md once S8c
// builds its renderer) → sidecar → PRAGMA optimize. The pipeline is built
// once, here, so S5b's and S6's verbs inherit the order instead of
// re-implementing it.
package verb

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Spoloborota/selftracked/internal/cli"
	"github.com/Spoloborota/selftracked/internal/dump"
	"github.com/Spoloborota/selftracked/internal/schema"
)

const (
	instanceDir = ".selftracked"
	dbFile      = "db.sqlite"
	dumpFile    = "dump.sql"
	hashFile    = "dump.hash"

	refusal = 1
	infra   = 2

	// codeDiverged marks every §8.4 divergence refusal.
	codeDiverged = "diverged"
	// codeNotFound marks a missing local instance.
	codeNotFound = "not-found"
)

// stateRender is the hook S8c fills with the STATE.md renderer; until
// then the slot exists (the §6.1 order is load-bearing) and renders
// nothing.
var stateRender = func(context.Context, *sql.DB, string) error { return nil }

// traceStep, when set by a white-box test, observes the pipeline's §6.1
// order — the order is a spec obligation (INV-180), so it must be
// assertable, not just implemented.
var traceStep func(step string)

func step(name string) {
	if traceStep != nil {
		traceStep(name)
	}
}

// now returns the one timestamp format any verb ever writes: ISO-8601
// UTC, generated by Go — no verb accepts a caller-supplied date (§5).
func now() string {
	return time.Now().UTC().Format("2006-01-02T15:04:05Z")
}

// versionGate is §8.6's gate. Every verb — read verbs included — begins
// with it, BEFORE the divergence check. At S5a it is still the S2-shaped
// stub; S11 fills in the migration escalation.
func versionGate() error { return nil }

// requireInstance says whether a database exists here.
func requireInstance() (string, error) {
	dbPath := filepath.Join(instanceDir, dbFile)
	if _, err := os.Stat(dbPath); err != nil {
		return "", &cli.CodedError{
			Code:    codeNotFound,
			Message: "no " + dbPath + " here; run selftracked init first",
			Status:  refusal,
		}
	}
	return dbPath, nil
}

// Write runs one write verb through the full pipeline. mutate runs inside
// the transaction and returns the events rows to append; everything after
// the commit is derived-file regeneration.
func Write(ctx context.Context, mutate func(tx *sql.Tx) ([]Event, error)) error {
	step("gate")
	if err := versionGate(); err != nil {
		return err
	}
	dbPath, err := requireInstance()
	if err != nil {
		return err
	}
	step("divergence")
	if err := divergenceCore(ctx, dbPath); err != nil {
		return err
	}

	// A pending gate-skip marker is folded into this verb's own transaction
	// (INV-277): the gate-skip event rides ahead of the verb's own events so
	// the one serialization pass that follows records both. `load` cannot
	// fold — it has no mutation — so it calls ConvertSkipMarker standalone.
	mutation, hadSkip, err := foldPendingSkip(mutate)
	if err != nil {
		return err
	}

	db, err := schema.OpenWrite(dbPath)
	if err != nil {
		return fmt.Errorf("open for write: %w", err)
	}
	defer func() { _ = db.Close() }()

	step("transaction")
	if err := mutateInTx(ctx, db, mutation); err != nil {
		return err
	}
	// Clear the marker only after its event has committed. If this fails the
	// event is already durable and the next write would re-convert the stale
	// marker into a duplicate gate-skip row — rare, and the returned error
	// tells the operator to remove .selftracked/skip-pending by hand.
	if hadSkip {
		if err := clearSkipMarker(); err != nil {
			return err
		}
	}
	return regenerateDerived(ctx, db)
}

// foldPendingSkip wraps mutate so that, when a gate-skip marker is pending,
// the gate-skip event is prepended to the verb's own events. It returns the
// (possibly wrapped) mutation and whether a marker was folded (so the caller
// clears it after commit).
func foldPendingSkip(mutate func(tx *sql.Tx) ([]Event, error)) (func(tx *sql.Tx) ([]Event, error), bool, error) {
	present, moment, err := readSkipMarker()
	if err != nil {
		return nil, false, err
	}
	if !present {
		return mutate, false, nil
	}
	wrapped := func(tx *sql.Tx) ([]Event, error) {
		events, err := mutate(tx)
		if err != nil {
			return nil, err
		}
		return append([]Event{gateSkipEvent(moment)}, events...), nil
	}
	return wrapped, true, nil
}

// mutateInTx is the transaction half: mutation plus its events rows,
// committed together or not at all.
func mutateInTx(ctx context.Context, db *sql.DB, mutate func(tx *sql.Tx) ([]Event, error)) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin: %w", err)
	}
	events, err := mutate(tx)
	if err != nil {
		_ = tx.Rollback()
		return err
	}
	stamp := now()
	for _, ev := range events {
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO events (at, entity, event, detail) VALUES (?, ?, ?, ?)`,
			stamp, ev.Entity, ev.Event, ev.Detail); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("events: %w", err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", err)
	}
	return nil
}

// regenerateDerived is the post-commit tail: the DB is already the local
// truth (§8.3), so a crash in here just leaves derived files stale for
// the next write to heal.
func regenerateDerived(ctx context.Context, db *sql.DB) error {
	step("dump")
	text, err := dump.Serialize(ctx, db)
	if err != nil {
		return fmt.Errorf("regenerate: %w", err)
	}
	if err := dump.WriteDumpFile(instanceDir, text); err != nil {
		return fmt.Errorf("regenerate: %w", err)
	}
	// §6.1's order puts STATE.md between the dump and the sidecar — found
	// as a latent order inversion by the S5a close review, fixed before
	// S8c's renderer could make it observable.
	step("state")
	if err := stateRender(ctx, db, instanceDir); err != nil {
		return err
	}
	step("sidecar")
	if err := dump.WriteSidecar(instanceDir, text); err != nil {
		return fmt.Errorf("regenerate: %w", err)
	}
	step("optimize")
	if _, err := db.ExecContext(ctx, `PRAGMA optimize`); err != nil {
		return fmt.Errorf("optimize: %w", err)
	}
	return nil
}

// Read runs one read verb: the same gate first (§6.1), then the body on a
// query_only connection — no side effects on tracker state.
func Read(ctx context.Context, body func(ctx context.Context, db *sql.DB) error) error {
	if err := versionGate(); err != nil {
		return err
	}
	dbPath, err := requireInstance()
	if err != nil {
		return err
	}
	db, err := schema.OpenRead(dbPath)
	if err != nil {
		return fmt.Errorf("open read-only: %w", err)
	}
	defer func() { _ = db.Close() }()
	return body(ctx, db)
}

// Event is one audit row a mutation produces. detail carries the verb's
// human-readable payload VERBATIM (§5.9).
type Event struct {
	Entity string
	Event  string
	Detail string
}

// divergenceCore is §8.4's decision procedure, the S5a core only:
// sidecar-anchored and total for the states verbs can reach —
// match / crash-residue heal / external-change refuse / missing sidecar.
// The migration-residue branch and prime's read-only report are S8b/S8c.
func divergenceCore(ctx context.Context, dbPath string) error {
	tracked, trackedErr := os.ReadFile(filepath.Join(instanceDir, dumpFile))
	sidecar, sidecarErr := os.ReadFile(filepath.Join(instanceDir, hashFile))
	if sidecarErr != nil {
		// A missing sidecar is divergent by safe default (§8.4): fresh
		// clones run `load` once.
		return &cli.CodedError{
			Code:    codeDiverged,
			Message: "no dump sidecar; run selftracked load first",
			Status:  refusal,
		}
	}
	if trackedErr != nil {
		return &cli.CodedError{
			Code:    codeDiverged,
			Message: "the tracked dump is missing; run selftracked dump (or load) first",
			Status:  refusal,
		}
	}
	sum := sha256.Sum256(tracked)
	if hex.EncodeToString(sum[:]) == strings.TrimSpace(string(sidecar)) {
		return nil // match: no external change (§8.4)
	}
	// Mismatch: regenerate from the DB in memory FIRST (§8.4).
	db, err := schema.OpenRead(dbPath)
	if err != nil {
		return fmt.Errorf("divergence check: %w", err)
	}
	defer func() { _ = db.Close() }()
	regen, err := dump.Serialize(ctx, db)
	if err != nil {
		return fmt.Errorf("divergence check: %w", err)
	}
	if string(regen) == string(tracked) {
		// Crash residue between dump write and sidecar update: heal the
		// sidecar and proceed.
		if err := dump.WriteSidecar(instanceDir, tracked); err != nil {
			return fmt.Errorf("heal sidecar: %w", err)
		}
		return nil
	}
	// The tracked dump changed under us (a pull, a checkout): writing
	// would clobber it with stale-DB content. Refuse, naming the fix.
	return &cli.CodedError{
		Code: codeDiverged,
		Message: "the tracked dump changed under this database; run selftracked load " +
			"(fast-forward to the pulled dump), then re-apply unsynced local writes through verbs",
		Status: refusal,
	}
}

// validateText enforces §8.1's write-time rule: control characters never
// enter the database, so the one-line-per-row dump grammar can never be
// broken by data. Every user-supplied string passes through here.
func validateText(flagName, s string) error {
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return &cli.CodedError{
				Code: "control-chars",
				Message: fmt.Sprintf(
					"%s contains a control character (0x%02x); dump rows are one line each",
					flagName, r),
				Status: refusal,
			}
		}
	}
	return nil
}
