package scaffold

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The generated hooks are POSIX sh (INV-436); these tests drive the ACTUAL
// generated bytes (read from the embedded template, so a template edit is
// covered) under /bin/sh with a stub `selftracked` on PATH. That stub lets
// each case force a branch — a verify rc, a failing dump, an untraced
// commit — without a real binary, which is the whole point of the hook's
// branch structure.

// stubScript is a fake `selftracked` whose every branch is steerable by env.
const stubScript = `#!/bin/sh
case "$1" in
  verify) exit ${STUB_VERIFY_RC:-0} ;;
  gate)
    if [ "$2" = skip-mark ]; then
      [ "${STUB_SKIP_FAIL:-0}" = 1 ] && exit 1
      mkdir -p .selftracked && : > .selftracked/skip-pending
      exit 0
    fi
    exit 0 ;;
  dump)  exit ${STUB_DUMP_RC:-0} ;;
  state) exit ${STUB_STATE_RC:-0} ;;
  stale) exit ${STUB_STALE_RC:-0} ;;
  config)
    # Mirror the real config ls: three keys, ORDER BY key (§6.2).
    if [ "$2" = ls ]; then
      echo "idle_days = ${STUB_IDLE:-14}"
      echo "prime_cap = ${STUB_CAP:-200}"
      echo "production_globs = ${STUB_GLOBS:-internal/**}"
    fi
    exit 0 ;;
  epic)
    if [ "$2" = list ] && [ -n "${STUB_EPICS:-}" ]; then
      for s in ${STUB_EPICS}; do echo "epic:$s [ACTIVE] goal"; done
    fi
    exit 0 ;;
  *) exit 0 ;;
esac
`

// hookBytes returns the generated hook script's exact bytes.
func hookBytes(t *testing.T, name string) []byte {
	t.Helper()
	b, err := templates.ReadFile("templates/hooks/" + name)
	if err != nil {
		t.Fatalf("read hook template %s: %v", name, err)
	}
	return b
}

// withStub writes the stub selftracked into a bin dir and returns a PATH
// with it in front. When install is false the bin dir is empty, so
// `command -v selftracked` fails — the binary-missing branch.
func withStub(t *testing.T, install bool) string {
	t.Helper()
	bin := t.TempDir()
	if install {
		if err := os.WriteFile(filepath.Join(bin, "selftracked"), []byte(stubScript), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	// Drop any inherited PATH directory carrying a real selftracked: the
	// binary-missing branch must hold on a machine where the tool is
	// installed — exactly the state the S10 self-host switchover creates.
	sep := string(os.PathListSeparator)
	kept := []string{bin}
	for dir := range strings.SplitSeq(os.Getenv("PATH"), sep) {
		// Empty and relative entries would be stat-checked against the
		// test process's cwd, not the hook's workdir — drop them outright.
		if dir == "" || !filepath.IsAbs(dir) {
			continue
		}
		if fi, err := os.Stat(filepath.Join(dir, "selftracked")); err == nil && fi.Mode()&0o111 != 0 {
			continue
		}
		kept = append(kept, dir)
	}
	return strings.Join(kept, sep)
}

// runScript runs a shell script file under /bin/sh in workdir with env
// overlaid on the process environment; returns stdout, stderr, exit code.
func runScript(t *testing.T, path, workdir string, env map[string]string, pathVar string) (string, string, int) {
	t.Helper()
	cmd := exec.Command("/bin/sh", path)
	cmd.Dir = workdir
	cmd.Env = append(os.Environ(), "PATH="+pathVar)
	for k, v := range env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	var out, errb strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errb
	err := cmd.Run()
	code := 0
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			code = ee.ExitCode()
		} else {
			t.Fatalf("run %s: %v", path, err)
		}
	}
	return out.String(), errb.String(), code
}

// writeHookFile writes the named generated hook into workdir and returns its
// path, executable.
func writeHookFile(t *testing.T, workdir, name string) string {
	t.Helper()
	p := filepath.Join(workdir, name)
	if err := os.WriteFile(p, hookBytes(t, name), 0o755); err != nil {
		t.Fatal(err)
	}
	return p
}

// TestGeneratedPreCommitBranches drives every rc-triage branch of the
// generated pre-commit (INV-426–433).
func TestGeneratedPreCommitBranches(t *testing.T) {
	cases := []struct {
		name       string
		env        map[string]string
		install    bool // stub selftracked on PATH?
		makeFiles  bool // create .selftracked/dump.sql + STATE.md so `git add` works
		wantExit   int
		wantStderr string
	}{
		// One row per pre-commit branch; INV refs in the function doc above.
		{"binary missing (INV-426)", nil, false, false, 0, "binary not installed"},
		{"skip (INV-427)", map[string]string{"SELFTRACKED_SKIP": "1"}, true, false, 0, ""},
		{
			"skip marker write fails (INV-427)",
			map[string]string{"SELFTRACKED_SKIP": "1", "STUB_SKIP_FAIL": "1"},
			true, false, 0, "could not record skip marker",
		},
		{"verify rc=2 (INV-428)", map[string]string{"STUB_VERIFY_RC": "2"}, true, false, 1, "did not complete"},
		{
			"verify signal death rc=130 (INV-428)",
			map[string]string{"STUB_VERIFY_RC": "130"},
			true, false, 1, "not bypassable as RED",
		},
		{"verify RED (INV-429)", map[string]string{"STUB_VERIFY_RC": "1"}, true, false, 1, "bypasses ONCE"},
		{"dump fails (INV-430)", map[string]string{"STUB_DUMP_RC": "1"}, true, false, 1, "dump refresh FAILED"},
		{"state fails (INV-431)", map[string]string{"STUB_STATE_RC": "1"}, true, false, 1, "STATE.md refresh FAILED"},
		{"git add fails (INV-432)", nil, true, false, 1, "staging dump/STATE.md FAILED"},
		{"green + staged echo (INV-432)", nil, true, true, 0, "staged refreshed dump.sql + STATE.md"},
		{"stale non-blocking (INV-433)", map[string]string{"STUB_STALE_RC": "1"}, true, true, 0, ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			work := t.TempDir()
			gitInit(t, work)
			hook := writeHookFile(t, work, "pre-commit")
			if c.makeFiles {
				if err := os.MkdirAll(filepath.Join(work, instanceDir), 0o750); err != nil {
					t.Fatal(err)
				}
				must(t, os.WriteFile(filepath.Join(work, instanceDir, dumpFile), []byte("-- d\n"), 0o644))
				must(t, os.WriteFile(filepath.Join(work, stateFile), []byte("# s\n"), 0o644))
			}
			_, stderr, code := runScript(t, hook, work, c.env, withStub(t, c.install))
			if code != c.wantExit {
				t.Errorf("exit = %d, want %d (stderr: %s)", code, c.wantExit, stderr)
			}
			if c.wantStderr != "" && !strings.Contains(stderr, c.wantStderr) {
				t.Errorf("stderr missing %q; got: %s", c.wantStderr, stderr)
			}
		})
	}
}

// TestGeneratedPostCommitWarnings covers the warn-only post-commit
// (INV-434 untraced, INV-435 sidecar mismatch). It always exits 0.
func TestGeneratedPostCommitWarnings(t *testing.T) {
	commitFile := func(t *testing.T, work, rel, content, msg string) {
		t.Helper()
		full := filepath.Join(work, rel)
		must(t, os.MkdirAll(filepath.Dir(full), 0o750))
		must(t, os.WriteFile(full, []byte(content), 0o644))
		gitCmd(t, work, "add", "-A")
		gitCmd(t, work, "commit", "-q", "-m", msg)
	}

	t.Run("untraced production commit warns", func(t *testing.T) { // INV-434
		work := newRepo(t)
		commitFile(t, work, "internal/x.go", "package x\n", "tidy up the internals")
		_, stderr, code := runScript(t, writeHookFile(t, work, "post-commit"), work, nil, withStub(t, true))
		if code != 0 {
			t.Fatalf("post-commit must exit 0, got %d", code)
		}
		if !strings.Contains(stderr, "untraced") {
			t.Errorf("expected untraced warning; got: %s", stderr)
		}
	})

	t.Run("task ref suppresses the warning", func(t *testing.T) { // INV-434 compliant
		work := newRepo(t)
		commitFile(t, work, "internal/x.go", "package x\n", "fix the parser #12")
		_, stderr, _ := runScript(t, writeHookFile(t, work, "post-commit"), work, nil, withStub(t, true))
		if strings.Contains(stderr, "untraced") {
			t.Errorf("a #NN message must suppress the warning; got: %s", stderr)
		}
	})

	t.Run("epic slug suppresses the warning", func(t *testing.T) { // INV-434 compliant
		work := newRepo(t)
		commitFile(t, work, "internal/x.go", "package x\n", "work on token-rotation")
		env := map[string]string{"STUB_EPICS": "token-rotation"}
		_, stderr, _ := runScript(t, writeHookFile(t, work, "post-commit"), work, env, withStub(t, true))
		if strings.Contains(stderr, "untraced") {
			t.Errorf("an epic slug must suppress the warning; got: %s", stderr)
		}
	})

	t.Run("sidecar mismatch warns", func(t *testing.T) { // INV-435
		work := newRepo(t)
		commitFile(t, work, ".selftracked/dump.sql", "-- committed dump A\n", "seed dump")
		// The sidecar names a DIFFERENT dump's hash — the signature of a
		// bypassed pre-commit that committed a stale dump.
		must(t, os.WriteFile(filepath.Join(work, instanceDir, "dump.hash"), []byte(sha256Hex("different bytes")+"\n"), 0o644))
		_, stderr, code := runScript(t, writeHookFile(t, work, "post-commit"), work, nil, withStub(t, true))
		if code != 0 {
			t.Fatalf("post-commit must exit 0, got %d", code)
		}
		if !strings.Contains(stderr, "does not match the sidecar") {
			t.Errorf("expected sidecar-mismatch warning; got: %s", stderr)
		}
	})

	t.Run("no false mismatch when dump.sql is absent from HEAD", func(t *testing.T) { // INV-435 false-positive guard
		work := newRepo(t)
		commitFile(t, work, "readme.md", "hi\n", "init readme") // HEAD has no dump.sql
		// A leftover local (gitignored) sidecar must NOT be read as a mismatch.
		must(t, os.MkdirAll(filepath.Join(work, instanceDir), 0o750))
		must(t, os.WriteFile(filepath.Join(work, instanceDir, "dump.hash"), []byte(sha256Hex("whatever")+"\n"), 0o644))
		_, stderr, _ := runScript(t, writeHookFile(t, work, "post-commit"), work, nil, withStub(t, true))
		if strings.Contains(stderr, "does not match the sidecar") {
			t.Errorf("no dump.sql in HEAD must not fire a mismatch warning; got: %s", stderr)
		}
	})

	t.Run("sidecar match is silent", func(t *testing.T) { // INV-435 negative
		work := newRepo(t)
		const dumpBytes = "-- committed dump A\n"
		commitFile(t, work, ".selftracked/dump.sql", dumpBytes, "seed dump")
		must(t, os.WriteFile(filepath.Join(work, instanceDir, "dump.hash"), []byte(sha256Hex(dumpBytes)+"\n"), 0o644))
		_, stderr, _ := runScript(t, writeHookFile(t, work, "post-commit"), work, nil, withStub(t, true))
		if strings.Contains(stderr, "does not match the sidecar") {
			t.Errorf("a matching sidecar must be silent; got: %s", stderr)
		}
	})
}

// TestChainingRecipeHazards demonstrates why the printed recipe's wording
// matters: exit propagation (INV-422) and subprocess-not-source (INV-424).
func TestChainingRecipeHazards(t *testing.T) {
	t.Run("exit propagation aborts the incumbent (INV-422)", func(t *testing.T) {
		work := newRepo(t)
		installGeneratedHook(t, work, "pre-commit")
		// The recipe line the incumbent adds: our hook, exit status propagated.
		incumbent := filepath.Join(work, "incumbent-pre-commit")
		must(t, os.WriteFile(incumbent, []byte(
			"#!/bin/sh\n.selftracked/hooks/pre-commit || exit $?\necho REACHED_INCUMBENT_TAIL\n"), 0o755))
		// Force our hook RED.
		_, _, code := runScript(t, incumbent, work, map[string]string{"STUB_VERIFY_RC": "1"}, withStub(t, true))
		if code == 0 {
			t.Errorf("a RED generated pre-commit must abort the chained incumbent (INV-422)")
		}
		out, _, _ := runScript(t, incumbent, work, map[string]string{"STUB_VERIFY_RC": "1"}, withStub(t, true))
		if strings.Contains(out, "REACHED_INCUMBENT_TAIL") {
			t.Errorf("propagation must stop the incumbent before its tail; got stdout: %s", out)
		}
	})

	t.Run("SELFTRACKED_SKIP bypasses only our gate; the incumbent's runs (INV-425)", func(t *testing.T) {
		work := newRepo(t)
		installGeneratedHook(t, work, "pre-commit")
		// The incumbent chains ours, then runs its OWN gate afterwards.
		incumbent := filepath.Join(work, "incumbent-pre-commit")
		must(t, os.WriteFile(incumbent, []byte(
			"#!/bin/sh\n.selftracked/hooks/pre-commit || exit $?\necho INCUMBENT_GATE_RAN\n"), 0o755))
		out, _, code := runScript(t, incumbent, work, map[string]string{"SELFTRACKED_SKIP": "1"}, withStub(t, true))
		if code != 0 {
			t.Fatalf("SELFTRACKED_SKIP must let the chained commit proceed (exit 0), got %d", code)
		}
		// Our gate is bypassed but still records the skip marker...
		if _, err := os.Stat(filepath.Join(work, instanceDir, "skip-pending")); err != nil {
			t.Errorf("INV-425: SELFTRACKED_SKIP must still record the skip marker: %v", err)
		}
		// ...and the incumbent's own gate is untouched — it still runs.
		if !strings.Contains(out, "INCUMBENT_GATE_RAN") {
			t.Errorf("INV-425: the incumbent's own gate must still run; got: %s", out)
		}
	})

	t.Run("source instead of subprocess skips the incumbent tail (INV-424)", func(t *testing.T) {
		work := newRepo(t)
		installGeneratedHook(t, work, "pre-commit")
		skip := map[string]string{"SELFTRACKED_SKIP": "1"} // an exit-0 branch that still `exit`s

		// Subprocess (correct): our hook exits in its own process; the tail runs.
		sub := filepath.Join(work, "incumbent-subprocess")
		must(t, os.WriteFile(sub, []byte("#!/bin/sh\n.selftracked/hooks/pre-commit\necho TAIL_RAN\n"), 0o755))
		out, _, _ := runScript(t, sub, work, skip, withStub(t, true))
		if !strings.Contains(out, "TAIL_RAN") {
			t.Errorf("subprocess execution must let the incumbent tail run; got: %s", out)
		}

		// Source (the hazard): our hook's internal `exit` terminates the
		// incumbent, skipping its tail.
		src := filepath.Join(work, "incumbent-source")
		must(t, os.WriteFile(src, []byte("#!/bin/sh\n. .selftracked/hooks/pre-commit\necho TAIL_RAN\n"), 0o755))
		out2, _, _ := runScript(t, src, work, skip, withStub(t, true))
		if strings.Contains(out2, "TAIL_RAN") {
			t.Errorf("sourcing must skip the incumbent tail — the hazard the recipe warns of; got: %s", out2)
		}
	})
}

// installGeneratedHook writes the named hook into .selftracked/hooks/ under
// work, mirroring where init puts it (the path the recipe references).
func installGeneratedHook(t *testing.T, work, name string) {
	t.Helper()
	dir := filepath.Join(work, hooksDir)
	must(t, os.MkdirAll(dir, 0o755))
	must(t, os.WriteFile(filepath.Join(dir, name), hookBytes(t, name), 0o755))
}

// --- small helpers ---

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatal(err)
	}
}

func gitCmd(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v: %s", strings.Join(args, " "), err, out)
	}
}

// newRepo makes a committable git repo (identity configured) and returns it.
func newRepo(t *testing.T) string {
	t.Helper()
	work := t.TempDir()
	gitInit(t, work)
	gitCmd(t, work, "config", "user.email", "t@example.invalid")
	gitCmd(t, work, "config", "user.name", "t")
	return work
}

func sha256Hex(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])
}
